# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
name: SMPLH
_target_: ems.transforms.rots2joints.SMPLH

jointstype: mmm
input_pose_rep: matrix
path: ${path.deps}/smplh
batch_size: ${machine.smpl_batch_size}
gender: neutral
