name: mtom
_target_: ems.model.textencoder.mtom.DistilbertActorAgnosticEncoder

latent_dim: ${model.latent_dim}
vae: ${model.vae}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
droupout: ${model.droupout}
activation: ${model.activation}

finetune: false
modelpath: ${path.deps}/distilbert-base-uncased