# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
version: 1

formatters:
  colorlog:
    (): colorlog.ColoredFormatter
    format: '[%(cyan)s%(asctime)s%(reset)s][%(purple)sHYDRA%(reset)s] %(message)s'
    datefmt: '%d/%m/%y %H:%M:%S'

handlers:
  console:
    class: rich.logging.RichHandler # logging.StreamHandler
    formatter: colorlog

root:
  level: INFO
  handlers:
  - console

disable_existing_loggers: false
