modelname: atemos_clf
_target_: ems.model.atemos_clf.TEMOSCLF
latent_dim: 256
num_classes: 53

vae: false
transforms: ${transforms}

if_clf: true

defaults:
  - discriminator: gru
  - losses: atemos_clf
  - optim: adamw
  - /model/losses/function/clf@func_clf