modelname: atemos_clf
_target_: ems.model.atemos_clf.TEMOS
latent_dim: 256
text_emb_size: 768
num_classes: 53

vae: false
transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
if_mask: false
temporal_window: 3
if_discriminator: true
if_bigen: false
if_humor: false
if_uniq: false
if_weighted: false
if_contrast: false
if_physics: false
if_clf: true

defaults:
  - textencoder: atom
  - textdecoder: actor
  - motionencoder: atom
  - motiondecoder: actor
  - discriminator: atom
  - losses: atemos_clf
  - optim: adamw
  - /model/losses/function/clf@func_clf