hydra:
  run:
    dir: .
  output_subdir: null


logger_level: INFO

defaults:
  - data: hybrikntu-amass-rot
  - machine: server
  - sampler: variable_conseq
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  transforms:
    normalization: false

transforms: ${data.transforms}