_target_: ems.model.losses.EMSComputeLosses

mode: ${transforms.ename}

# Loss terms
## Reconstruction losses
lmd_text2rfeats_recons: 2.0
lmd_rfeats_recons: 1.0
lmd_text_recons: 1.0
lmd_jfeats_recons: 1.0
lmd_connect_recons: 1.0

## Latent spaces losses
lmd_latent: 1.0e-5
lmd_kl: 1.0e-5

## contrastive losses
lmd_text_contrast: 1.0e-3
lmd_motion_contrast: 1.0e-3

# Ablations
loss_on_both: true

force_loss_on_jfeats: false
ablation_no_kl_combine: false
ablation_no_kl_gaussian: false
ablation_no_motionencoder: false
humor: ${model.if_humor}
contrast: ${model.if_contrast}

# Late => rfeats (prev features)
recons_connect2connect: ${.lmd_connect_recons}
recons_connect2connect_func: ${model.func_recons}

# Text => rfeats (rotation features)
recons_text2rfeats: ${.lmd_text2rfeats_recons}
recons_text2rfeats_func: ${model.func_recons}

# Text => Humor
recons_text2humor: ${.lmd_rfeats_recons}
recons_text2humor_func: ${model.func_recons}

# Text => jfeats (xyz features)
recons_text2jfeats: ${.lmd_jfeats_recons}
recons_text2jfeats_func: ${model.func_recons}

# rfeats => rfeats
recons_rfeats2rfeats: ${.lmd_rfeats_recons}
recons_rfeats2rfeats_func: ${model.func_recons}

# jfeats => jfeats
recons_jfeats2jfeats: ${.lmd_jfeats_recons}
recons_jfeats2jfeats_func: ${model.func_recons}

# Latent space losses
latent_manifold: ${.lmd_latent}
latent_manifold_func: ${model.func_latent}
latent_humor: ${.lmd_latent}
latent_humor_func: ${model.func_latent}

# VAE losses
kl_connect: ${.lmd_kl}
kl_connect_func: ${model.func_kl}

kl_text: ${.lmd_kl}
kl_text_func: ${model.func_kl}

kl_motion: ${.lmd_kl}
kl_motion_func: ${model.func_kl}

kl_text2motion: ${.lmd_kl}
kl_text2motion_func: ${model.func_kl}

kl_motion2text: ${.lmd_kl}
kl_motion2text_func: ${model.func_kl}

kl_text2humor: ${.lmd_kl}
kl_text2humor_func: ${model.func_kl}

# Contrast Losses
text_contrast: ${.lmd_text_contrast}
text_contrast_func: ${model.func_contrast}
motion_contrast: ${.lmd_motion_contrast}
motion_contrast_func: ${model.func_contrast}